- hosts: 127.0.0.1 
  connection: local
  gather_facts: no
  tasks:
    - name: Create IAM user
      iam:
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}" 
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}" 
        ec2_region: "{{ lookup('env', 'AWS_REGION') }}" 
        iam_type: user
        state: present
        name: linuxacademy
        password: mypass
    - name: Create new group with policy and add user
      iam_group:
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}" 
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}" 
        ec2_region: "{{ lookup('env', 'AWS_REGION') }}" 
        name: testgroup
        managed_policy: 
          - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
        users: 
          - linuxacademy
        state: present
