---
- hosts: all
  tasks:
          - name: 'Install SO dependencies'
            apt: 
                name: "{{ item }}"
                state: latest
            become: yes
            with_items:
                    - php5
                    - apache2
                    - libapache2-mod-php5
                    - php5-gd
                    - libssh2-php
                    - php5-mcrypt
                    - mysql-server-5.6
                    - python-mysqldb
                    - php5-mysql
                    - unzip
                    - tar

          - name: 'Install a MySQL database'
            mysql_db: 
               name: wordpress_db
               login_user: root
               state: present

          - name: 'Make a user wordpress'
            mysql_user:
               login_user: 
               name: wordpress_user
               password: 
               priv: 'wordpress_db.*:ALL'
               state: present
          
          - name: 'Download wordpress' 
            get_url:
               url: 'https://wordpress.org/latest.tar.gz'
               dest: '/tmp/wordpress.tar.gz'

          - name: 'Decompress wordpress file'
            unarchive: 
               src: '/tmp/wordpress.tar.gz'
               dest: /var/www/
               remote_src: yes
            become: yes 
